defaults:
- data: zarr
- dataloader: multi_domain
- datamodule: single
- diagnostics: evaluation
- hardware: slurm
- graph: multi_domain_stretched
- model: graphtransformer_multi_domain
- training: multi_domain_stretched
- _self_
#- override hydra/hydra_logging: disabled
- override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .
### This file is for local experimentation.
## When you commit your changes, assign the new features and keywords
## to the correct defaults.
config_validation: False

data:
  resolution: None
  forcing:
  - "cos_latitude"
  - "cos_longitude"
  - "sin_latitude"
  - "sin_longitude"
  - "cos_julian_day"
  - "cos_local_time"
  - "sin_julian_day"
  - "sin_local_time"
  - "insolation"
  - "lsm"
  - "z"

  diagnostic:
  - "tp"

  normalizer:
    max: 
    - "z"
    none:
    - "cos_latitude"
    - "cos_longitude"
    - "sin_latitude"
    - "sin_longitude"
    - "cos_julian_day"
    - "cos_local_time"
    - "sin_julian_day"
    - "sin_local_time"
    - "insolation"
    - "lsm"

graph:
  overwrite: False
  clobber: False
  # graph already built separate graph build
  # for SG and global is not yet implemented
  # has to be defined prior.

diagnostics:
  log:
    mlflow:
      enabled: True
      offline: True
      authentication: True
      experiment_name: metno #multi-domain-experiments
      project_name: Anemoi
      log_model: False
      tracking_uri: https://mlflow.ecmwf.int
      run_name: md4-n32-s4-lr-5e-6-bs32
    wandb:
      enabled: False
  print_memory_summary: True
  show_entire_globe: False

hardware:
  files:
    warm_start: last.ckpt
    dataset: null
    graph: null
  paths:
    warm_start: /leonardo_work/DestE_330_25/users/sbuurman/multi-domain-training/output/european_model/
    data: /leonardo_work/DestE_330_25/anemoi/datasets/
    output: /leonardo_work/DestE_330_25/users/sbuurman/multi-domain-training/output/
    graph: /leonardo_work/DestE_330_25/users/sbuurman/graphs/
  num_gpus_per_node: ${oc.decode:${oc.env:SLURM_GPUS_PER_NODE}}
  num_nodes: ${oc.decode:${oc.env:SLURM_NNODES}}
  num_gpus_per_model: 4

model:
  keep_batch_sharded: False
  dynamic_mode: True
  num_channels: 1024
  trainable_parameters:
    data: 0
    hidden: 0
    data2hidden: 0
    hidden2data: 0
    hidden2hidden: 0

training:
  run_id: null 
  fork_run_id: null
  transfer_learning: True
  load_weights_only: True
  max_steps: 13500 

  node_loss_weights:
    MEPS:
      _target_: anemoi.training.losses.nodeweights.ReweightedGraphNodeAttribute
      target_nodes: ${graph.data}
      node_attribute: area_weight
      scaled_attribute: cutout
      weight_frac_of_total: 0.23
    ARA:
      _target_: anemoi.training.losses.nodeweights.ReweightedGraphNodeAttribute
      target_nodes: ${graph.data}
      node_attribute: area_weight
      scaled_attribute: cutout
      weight_frac_of_total: 0.10
    AA:
      _target_: anemoi.training.losses.nodeweights.ReweightedGraphNodeAttribute
      target_nodes: ${graph.data}
      node_attribute: area_weight
      scaled_attribute: cutout
      weight_frac_of_total: 0.23
    UWC:
      _target_: anemoi.training.losses.nodeweights.ReweightedGraphNodeAttribute
      target_nodes: ${graph.data}
      node_attribute: area_weight
      scaled_attribute: cutout
      weight_frac_of_total: 0.50
    TITAN:
      _target_: anemoi.training.losses.nodeweights.ReweightedGraphNodeAttribute
      target_nodes: ${graph.data}
      node_attribute: area_weight
      scaled_attribute: cutout
      weight_frac_of_total: 0.15

  lr:
    rate: 5e-6 #5e-6  # local_lr
    iterations: ${training.max_steps}  # NOTE: When max_epochs < max_steps, scheduler will run for max_steps
    min: 3e-7  # Not scaled by #GPU
    warmup_t: 1000 #1500

  validation_metrics:
    - _target_: anemoi.training.losses.mse.WeightedMSELoss
      scalars: []
      ignore_nans: True
    - _target_: anemoi.training.losses.multidomain_mse.MultiDomainMSELoss
      loss_name: "MEPS"
      ignore_nans: True
    - _target_: anemoi.training.losses.multidomain_mse.MultiDomainMSELoss
      loss_name: "ARA"
      ignore_nans: True
    - _target_: anemoi.training.losses.multidomain_mse.MultiDomainMSELoss
      loss_name: "AA"
      ignore_nans: True
    - _target_: anemoi.training.losses.multidomain_mse.MultiDomainMSELoss
      loss_name: "UWC"
      ignore_nans: True
    - _target_: anemoi.training.losses.multidomain_mse.MultiDomainMSELoss
      loss_name: "TITAN"
      ignore_nans: True


dataloader:
  num_workers:
    training: 1
    validation: 1
    test: 1
    predict: 1
  limit_batches:
    training: null
    validation: null

  training_periods:
    MEPS: # Stretched-grid
      start: 2021-10-02 #oper-ea-an-2016-2023
      end: 2023-09-30 #2022-05-31
    ARA: # Stretched-grid
      start: 2012-01-01 #oper-ea-an-2016-2023
      end: 2020-09-30
    AA: # Stretched-grid
      start: 2017-01-01 #oper-ea-an-2016-2023
      end: 2020-09-30
    UWC: # Stretched-grid
      start: 2021-10-02 #2020-10-01 06:00:00 #oper-ea-an-2016-2023
      end: null #2022-08-31
    TITAN:
      start: 2021-10-02
      end: 2024-10-18

  validation_periods:
    MEPS:
      start: 2020-10-01
      end: 2021-10-01
    ARA:
      start: 2020-11-01
      end: 2021-10-01
    AA:
      start: 2020-10-01
      end: 2021-10-01
    UWC:
      start: 2020-10-01
      end: 2021-10-01
    TITAN:
      start: 2020-10-01
      end: 2021-10-01

  regional_datasets:
    MEPS:
      dataset: /leonardo_work/DestE_330_25/anemoi/datasets/MEPS/aifs-meps-2.5km-2020-2023-6h-v7.zarr
      trim_edge: 50
    ARA:
      dataset: /leonardo_work/DestE_330_25/anemoi/datasets/ARA/6HR/geosphere-00-ara-2p5km-2012-2021-6h-accummulations-v12.zarr
      drop: tp
      rename: {"tp_6h": "tp"}
    AA:
      dataset: /leonardo_work/DestE_330_25/anemoi/datasets/AROME-ARCTIC/arome_arctic-2.5km-2022-2025-6h-v4.zarr
      trim_edge: 50
    UWC:
      dataset: /leonardo_work/DestE_330_25/anemoi/datasets/UWC-West/uwcwest-rr-an-oper-0001-mars-2p0km-2020-2023-3h-v3-knmi.zarr
      rename: {"tp_6h": "tp"}
    TITAN:
      dataset: /leonardo_work/DestE_330_25/anemoi/datasets/TITAN/arome-an-oper-titan-0p025-2020-2024-1h-v4-eurw-precip6.zarr

  dataset:
    cutout:
      - dataset: /leonardo_work/DestE_330_25/anemoi/datasets/MEPS/aifs-meps-2.5km-2020-2023-6h-v7.zarr
      - concat:
        - join:
          - concat:
            - dataset: /leonardo_work/DestE_330_25/anemoi/datasets/ERA5/aifs-ea-an-oper-0001-mars-n320-1979-2022-6h-v6.zarr
              start: null
              end: 2022-12-31
              reorder: sort
            - dataset: /leonardo_work/DestE_330_25/anemoi/datasets/ERA5/aifs-od-an-oper-0001-mars-n320-2019-2023-6h-v6.zarr
              start: 2023-01-01
              end: null
              drop:
              reorder: sort
          - dataset: /leonardo_work/DestE_330_25/anemoi/datasets/ERA5/aifs-ea-an-oper-0001-mars-n320-1979-2023-6h-v1-land.zarr
          reorder: sort
        - dataset: /leonardo_work/DestE_330_25/anemoi/datasets/IFS/aifs-od-an-oper-0001-mars-n320-2024-2025-6h-v1.zarr
          reorder: sort
    min_distance_km: 0
    adjust: all
    reorder: sort
    select: ['10u', '10v', '2d', '2t', 'cos_julian_day', 'cos_latitude', 'cos_local_time', 'cos_longitude', 'insolation', 'lsm', 'msl', 'q_100', 'q_1000', 'q_150', 'q_200', 'q_300', 'q_400', 'q_500', 'q_700', 'q_850', 'q_925', 'sin_julian_day', 'sin_latitude', 'sin_local_time', 'sin_longitude', 'skt', 'sp', 't_100', 't_1000', 't_150', 't_200', 't_300', 't_400', 't_500', 't_700', 't_850', 't_925', 'tp', 'u_100', 'u_1000', 'u_150', 'u_200', 'u_300', 'u_400', 'u_500', 'u_700', 'u_850', 'u_925', 'v_100', 'v_1000', 'v_150', 'v_200', 'v_300', 'v_400', 'v_500', 'v_700', 'v_850', 'v_925', 'w_100', 'w_1000', 'w_150', 'w_200', 'w_300', 'w_400', 'w_500', 'w_700', 'w_850', 'w_925', 'z', 'z_100', 'z_1000', 'z_150', 'z_200', 'z_300', 'z_400', 'z_500', 'z_700', 'z_850', 'z_925']
    statistics: /leonardo_work/DestE_330_25/anemoi/datasets/ERA5/aifs-od-an-oper-0001-mars-n320-2019-2023-6h-v6.zarr