defaults:
  - data: zarr
  - dataloader: multi_domain
  - diagnostics: evaluation
  - hardware: slurm
  - graph: multi_domain_stretch
  - model: dynamic_graphtransformer
  - training: default
  - _self_

### This file is for local experimentation.
## When you commit your changes, assign the new features and keywords
## to the correct defaults.
## to the correct defaults.

graph:
  overwrite: True
  nodes:
    hidden:
      node_builder:
        _target_: anemoi.graphs.nodes.StretchedTriNodes
        lam_resolution: 10
        global_resolution: 7
        reference_node_name: ${graph.data}
        mask_attr_name: cutout
        margin_radius_km: 11

diagnostics:
  log:
    mlflow:
      enabled: False
      offline: False
      authentication: True
      experiment_name: multi-domain-experiments
      project_name: Anemoi
      log_model: False
      tracking_uri: https://mlflow.ecmwf.int
      run_name: md-MEPS-test-lr_025e-6_12k_iter_bs_16
    wandb:
      enabled: False
  print_memory_summary: True
  show_entire_globe: False

hardware:
  files:
    warm_start: null #"/pfs/lustrep4/scratch/project_465000527/anemoi/experiments/n320_arome_meps_pretrain/anemoi-by_epoch-epoch_038-step_019503.ckpt"
    graph: 
  paths:
    # graph: /pfs/lustrep4/scratch/project_465000527/salihiar/multi-domain-setup/graphs
    graph: /pfs/lustrep4/scratch/project_465000527/buurmans/DE_330_WP14/Anemoi/multi-domain-training/output/graphs/
    output: /pfs/lustrep4/scratch/project_465000527/buurmans/DE_330_WP14/Anemoi/multi-domain-training/output/
  num_gpus_per_node: ${oc.decode:${oc.env:SLURM_GPUS_PER_NODE}}
  num_nodes: ${oc.decode:${oc.env:SLURM_NNODES}}
  num_gpus_per_model: 8

model:
  num_channels: 1024

training:
  runtime: 
    _target_: anemoi.training.train.train.AnemoiMultiDomainTrainer
  run_id: null #checkpoint/3fb85b72ba9647d5ae4fe86ce1b5a885
  # fork_run_id: 3fb85b72ba9647d5ae4fe86ce1b5a885
  fork_run_id: null
  transfer_learning: False
  mapping_weights: 
    layer_norm_attention_src: layer_norm1
    layer_norm_attention_dest: layer_norm2
    layer_norm_attention: layer_norm1
    layer_norm_mlp: layer_norm2
  load_weights_only: False
  max_steps: 10000

  node_loss_weights:
    MEPS:
      _target_: anemoi.training.losses.nodeweights.ReweightedGraphNodeAttribute
      target_nodes: ${graph.data}
      node_attribute: area_weight
      scaled_attribute: cutout
      weight_frac_of_total: 0.23

  lr:
    rate: 6e-6  # local_lr
    iterations: ${training.max_steps}  # NOTE: When max_epochs < max_steps, scheduler will run for max_steps
    min: 3e-7  # Not scaled by #GPU
    warmup_t: 1000

  validation_metrics:
    - _target_: anemoi.training.losses.mse.WeightedMSELoss
      scalars: []
      ignore_nans: True
    - _target_: anemoi.training.losses.multidomain_mse.MultiDomainMSELoss
      loss_name: "MEPS"
      ignore_nans: True

dataloader:
  num_workers:
    training: 4
    validation: 4
    test: 1
    predict: 1
  limit_batches:
    training: null
    validation: null

  training_periods:
    MEPS:
      start: 2020-02-05
      end: 2022-05-31

  validation_periods:
    MEPS:
      start: 2022-06-01
      end: 2023-05-31

  regional_datasets:
    MEPS:
      dataset: /pfs/lustrep4/scratch/project_465000527/anemoi/datasets/MEPS/aifs-meps-2.5km-2020-2024-6h-v6.zarr

  datasets:
    cutout:
      - dataset: null  # Fixed `null` value
      - dataset: ${hardware.paths.data}/aifs-od-an-oper-0001-mars-n320-2019-2023-6h-v6.zarr
    adjust: ["all"]
    statistics: ${hardware.paths.data}/aifs-od-an-oper-0001-mars-n320-2019-2023-6h-v6.zarr

