defaults:
- data: zarr
- dataloader: multi_domain
- diagnostics: evaluation
- hardware: slurm
- graph: multi_domain_stretch
- model: dynamic_graphtransformer
- training: default
- _self_


### This file is for local experimentation.
##  When you commit your changes, assign the new features and keywords
##  to the correct defaults.
# For example to change from default GPU count:
# hardware:
#   num_gpus_per_node: 1
graph:
  overwrite: False
  nodes:
    hidden:
      node_builder:
        _target_: anemoi.graphs.nodes.StretchedTriNodes
        lam_resolution: 10
        global_resolution: 7
        reference_node_name: ${graph.data}
        mask_attr_name: cutout
        margin_radius_km: 11

diagnostics:
  log:
    mlflow:
      enabled: True
      offline: False
      authentication: True
      experiment_name: 'multi-domain-experiments'
      project_name: 'Anemoi'
      log_model: False
      tracking_uri: 'https://mlflow.ecmwf.int'
    wandb:
      enabled: False
  print_memory_summary: True
  show_entire_globe: False
hardware:
  files: 
    warm_start: /pfs/lustrep4/scratch/project_465000527/anemoi/experiments/n320_arome_meps_pretrain/anemoi-by_epoch-epoch_038-step_019503.ckpt
  num_gpus_per_node: 8
  num_nodes: 1
  num_gpus_per_model: 8
model:
  num_channels: 1024
training:
  run_id: 
  transfer_learning: True
  load_weights_only: True
  max_steps: 12000
  node_loss_weights:
    MEPS:
      _target_: anemoi.training.losses.nodeweights.ReweightedGraphNodeAttribute
      target_nodes: ${graph.data}
      scaled_attribute: cutout
      weight_frac_of_total: 0.23
      node_attribute: area_weight
    AA:
      _target_: anemoi.training.losses.nodeweights.ReweightedGraphNodeAttribute
      target_nodes: ${graph.data}
      scaled_attribute: cutout
      weight_frac_of_total: 0.23
      node_attribute: area_weight

  lr:
    rate: 0.4e-5 #local_lr
    iterations: ${training.max_steps} # NOTE: When max_epochs < max_steps, scheduler will run for max_steps
    min: 3e-7 #Not scaled by #GPU
    warmup_t: 1000

  validation_metrics: 
    #loss class to initialise
    - _target_: anemoi.training.losses.mse.WeightedMSELoss
      # Scalars to include in loss calculation
      # Cannot scale over the variable dimension due to possible remappings.
      # Available scalars include:  
      # - 'loss_weights_mask': Giving imputed NaNs a zero weight in the loss function
      # Use the `scale_validation_metrics` section to variable scale.
      scalars: []
      # other kwargs
      ignore_nans: True
    - _target_: anemoi.training.losses.limitedarea.WeightedMSELossLimitedArea
      scalars: ['limited_area_mask_MEPS', 'limited_area_mask_AA']
      inside_lam: True
      wmse_contribution: False
      ignore_nans: True
    - _target_: anemoi.training.losses.multidomain_mse.MultiDomainMSELoss
      scalars: ['limited_area_mask_AA']
      loss_name: "AA"
      inside_lam: True
      wmse_contribution: False
      ignore_nans: True
    - _target_: anemoi.training.losses.multidomain_mse.MultiDomainMSELoss
      scalars: ['limited_area_mask_MEPS']
      loss_name: "MEPS"
      inside_lam: True
      wmse_contribution: False
      ignore_nans: True


dataloader:
  num_workers:
    training: 6
    validation: 6
    test: 1
    predict: 1
  limit_batches:
    training: 400
    validation: 140
  training_periods:
    MEPS:
      start: 2020-02-05 
      end: 2022-05-31
    AA:
      start: 2017-01-01
      end: 2022-05-31

  validation_periods:
    MEPS:
      start: 2022-06-01 
      end: 2023-05-31
    AA:
      start: 2022-06-01
      end: 2022-12-31

  regional_datasets:
    MEPS: 
      dataset: /pfs/lustrep4/scratch/project_465000527/anemoi/datasets/MEPS/aifs-meps-2.5km-2020-2024-6h-v6.zarr
    AA: 
      dataset: /pfs/lustrep4/scratch/project_465000527/anemoi/datasets/AROME-ARCTIC/arome_arctic-2_5km-2017-2024.zarr

  select: 
      - 10u
      - 10v
      - 2d
      - 2t
      - cos_julian_day
      - cos_latitude
      - cos_local_time
      - cos_longitude
      - insolation
      - lsm
      - msl
      - q_100
      - q_1000
      - q_150
      - q_200
      - q_250
      - q_300
      - q_400
      - q_50
      - q_500
      - q_700
      - q_850
      - q_925
      - sin_julian_day
      - sin_latitude
      - sin_local_time
      - sin_longitude
      - skt
      - sp
      - t_100
      - t_1000
      - t_150
      - t_200
      - t_250
      - t_300
      - t_400
      - t_50
      - t_500
      - t_700
      - t_850
      - t_925
      - tcw
      - tp
      - u_100
      - u_1000
      - u_150
      - u_200
      - u_250
      - u_300
      - u_400
      - u_50
      - u_500
      - u_700
      - u_850
      - u_925
      - v_100
      - v_1000
      - v_150
      - v_200
      - v_250
      - v_300
      - v_400
      - v_50
      - v_500
      - v_700
      - v_850
      - v_925
      - w_100
      - w_1000
      - w_150
      - w_200
      - w_250
      - w_300
      - w_400
      - w_50
      - w_500
      - w_700
      - w_850
      - w_925
      - z
      - z_100
      - z_1000
      - z_150
      - z_200
      - z_250
      - z_300
      - z_400
      - z_50
      - z_500
      - z_700
      - z_850
      - z_925

