defaults:
- data: zarr
- dataloader: multi_domain
- diagnostics: evaluation
- hardware: slurm
- graph: multi_domain_stretch
- model: dynamic_graphtransformer
- training: default
- _self_


### This file is for local experimentation.
##  When you commit your changes, assign the new features and keywords
##  to the correct defaults.
# For example to change from default GPU count:
# hardware:
#   num_gpus_per_node: 1
graph:
  overwrite: False
  nodes:
    hidden:
      node_builder:
        _target_: anemoi.graphs.nodes.StretchedTriNodes
        lam_resolution: 5
        global_resolution: 3
        reference_node_name: ${graph.data}
        mask_attr_name: cutout
        margin_radius_km: 11

diagnostics:
  log:
    interval: 10
    mlflow:
      enabled: True
      offline: False
      authentication: True
      experiment_name: 'knmi-lumi-anemoi-cerra-sg'
      project_name: 'Anemoi'
      log_model: False
      tracking_uri: 'https://mlflow.ecmwf.int'
    wandb:
      enabled: False
  print_memory_summary: True
  show_entire_globe: False
  plot:
    asynchronous: True # Whether to plot asynchronously
    datashader: True # Choose which technique to use for plotting
    frequency: # Frequency of the plotting
      batch: 10
      epoch: 1
    # Parameters to plot
    parameters:
    - z_500
    - t_850
    - u_850
    - v_850
    - 2t
    - 10u
    - 10v
    - sp
    - tp

    # Sample index
    sample_idx: 0

    callbacks: []
      # - _target_: anemoi.training.diagnostics.callbacks.plot.PlotSample
      #   sample_idx: 0
      #   per_sample : 6
      #   parameters: ["z_500", "t_850", "u_850", "v_850", "2t", "10u", "10v", "sp", "tp"]
      #   #Defining the accumulation levels for precipitation related fields and the colormap
      #   accumulation_levels_plot: [0, 0.05, 0.1, 0.25, 0.5, 1, 1.5, 2, 3, 4, 5, 6, 7, 100] # in mm
      #   cmap_accumulation: ["#ffffff", "#04e9e7", "#019ff4", "#0300f4", "#02fd02", "#01c501", "#008e00", "#fdf802", "#e5bc00", "#fd9500", "#fd0000", "#d40000", "#bc0000", "#f800fd"]
      #   precip_and_related_fields: ["tp"]
hardware:
  files: 
    warm_start: /pfs/lustrep4/scratch/project_465000527/anemoi/experiments/n320_arome_meps_pretrain/anemoi-by_epoch-epoch_038-step_019503.ckpt
  num_gpus_per_node: 8
  num_nodes: 1
  num_gpus_per_model: 8
model:
  num_channels: 1024
  # output_mask: cutout # it must be a node attribute of the output nodes
dataloader:
  num_workers:
    training: 1
    validation: 1
    test: 1
    predict: 1
  limit_batches:
    training: 10
    validation: 10
  #new
  training_periods:
    MEPS:
      start: 2020-02-05 
      end: 2023-05-31
    ARA:
      start: 2012-01-01
      end: 2015-12-31

  #new
  validation_periods:
    MEPS:
      start: 2023-06-01
      end: 2024-05-31
    ARA:
      start: 2016-01-01
      end: 2016-12-31

  #new
  regional_datasets:
    MEPS: 
      dataset: /pfs/lustrep4/scratch/project_465000527/anemoi/datasets/MEPS/aifs-meps-2.5km-2020-2024-6h-v6.zarr
    ARA: 
      dataset: /pfs/lustrep4/scratch/project_465000527/ARA_Data/Zarr/aut-rd-an-oper-0001-ara-2p5km-20120101_20181231-3h-v7.zarr
  
  select: 
      - 2t
      - 2d
      - 10u
      - 10v
      - msl
      - sp
      - lsm
      - z
      - tp
      - skt
      - tcw
      - u_50
      - u_100
      - u_150
      - u_200
      - u_250
      - u_300
      - u_400
      - u_500
      - u_700
      - u_850
      - u_925
      - u_1000
      - v_50
      - v_100
      - v_150
      - v_250
      - v_200
      - v_300
      - v_400
      - v_500
      - v_700
      - v_850
      - v_925
      - v_1000
      - w_50
      - w_100
      - w_150
      - w_200
      - w_250
      - w_300
      - w_400
      - w_500
      - w_700
      - w_850
      - w_925
      - w_1000
      - t_50
      - t_100
      - t_150
      - t_200
      - t_250
      - t_300
      - t_400
      - t_500
      - t_700
      - t_850
      - t_925
      - t_1000
      - q_50
      - q_100
      - q_150
      - q_200
      - q_250
      - q_300
      - q_400
      - q_500
      - q_700
      - q_850
      - q_925
      - q_1000
      - z_50
      - z_100
      - z_150
      - z_200
      - z_250
      - z_300
      - z_400
      - z_500
      - z_700
      - z_850
      - z_925
      - z_1000
      - "cos_latitude"
      - "cos_longitude"
      - "sin_latitude"
      - "sin_longitude"
      - "cos_julian_day"
      - "cos_local_time"
      - "sin_julian_day"
      - "sin_local_time"
      - "insolation"
training:
  max_epochs: 20
  run_id: 
  transfer_learning: True
  load_weights_only: True
  validation_metrics:
    # loss class to initialise
    - _target_: anemoi.training.losses.mse.WeightedMSELoss
      # Scalars to include in loss calculation
      # Cannot scale over the variable dimension due to possible remappings.
      # Available scalars include:  
      # - 'loss_weights_mask': Giving imputed NaNs a zero weight in the loss function
      # Use the `scale_validation_metrics` section to variable scale.
      scalars: []
      # other kwargs
      ignore_nans: True
    - _target_: anemoi.training.losses.limitedarea.WeightedMSELossLimitedArea
      scalars: ['limited_area_mask_MEPS', 'limited_area_mask_ARA']
      inside_lam: True
      wmse_contribution: False
      ignore_nans: True
    - _target_: anemoi.training.losses.multidomain_mse.MultiDomainMSELoss
      scalars: ['limited_area_mask_ARA']
      loss_name: "ARA"
      inside_lam: True
      wmse_contribution: False
      ignore_nans: True
    - _target_: anemoi.training.losses.multidomain_mse.MultiDomainMSELoss
      scalars: ['limited_area_mask_MEPS']
      loss_name: "MEPS"
      inside_lam: True
      wmse_contribution: False
      ignore_nans: True




