defaults:
- data: zarr
- dataloader: multi_domain
- diagnostics: evaluation
- hardware: slurm
- graph: multi_domain_stretch
- model: dynamic_graphtransformer
- training: default
- _self_


### This file is for local experimentation.
##  When you commit your changes, assign the new features and keywords
##  to the correct defaults.
# For example to change from default GPU count:
# hardware:
#   num_gpus_per_node: 1

diagnostics:
  log:
    interval: 100
    mlflow:
      enabled: False
      offline: False
      authentication: True
      experiment_name: 'multi-domain-experiments'
      project_name: 'Anemoi'
      log_model: False
      tracking_uri: 'https://mlflow.ecmwf.int'
    wandb:
      enabled: False
  print_memory_summary: True
  show_entire_globe: False
hardware:
  files:
    warm_start: /pfs/lustrep4/scratch/project_465000527/buurmans/DE_330_WP14/Anemoi/multi-domain-training/checkpoints/ERA5_checkpoints/4b23cfdc-f24f-428a-98ce-1c800979e30a/4b23cfdc-f24f-428a-98ce-1c800979e30a.ckpt
  num_gpus_per_node: 8
  num_nodes: 1
  num_gpus_per_model: 8
model:
  num_channels: 128
training:
  transfer_learning: True
  load_weights_only: True
  fork_run_id: 4b23cfdc-f24f-428a-98ce-1c800979e30a
  lr:
    rate: 0.04e-4 #local_lr
  validation_metrics:
    # loss class to initialise
    - _target_: anemoi.training.losses.mse.WeightedMSELoss
      # Scalars to include in loss calculation
      # Cannot scale over the variable dimension due to possible remappings.
      # Available scalars include:  
      # - 'loss_weights_mask': Giving imputed NaNs a zero weight in the loss function
      # Use the `scale_validation_metrics` section to variable scale.
      scalars: []
      # other kwargs
      ignore_nans: True
    - _target_: anemoi.training.losses.multidomain_mse.MultiDomainMSELoss
      loss_name: "CERRA"
      ignore_nans: True
    - _target_: anemoi.training.losses.multidomain_mse.MultiDomainMSELoss
      loss_name: "MEPS"
      ignore_nans: True

dataloader:
  limit_batches:
    training: 100
    validation: 100

  #new
  training_periods:
    MEPS:
      start: 2020-02-05 
      end: 2023-05-31
    CERRA:
      start: null
      end: "2018-12-31"

  #new
  validation_periods:
    MEPS:
      start: 2023-06-01
      end: 2024-05-31
    CERRA:
      start: "2019-01-01"
      end: "2019-12-31"

  # new
  regional_datasets:
    MEPS: 
      dataset: /pfs/lustrep4/scratch/project_465000527/anemoi/datasets/MEPS/aifs-meps-2.5km-2020-2024-6h-v6.zarr
    CERRA: 
      dataset: 
        join:
          - dataset: /pfs/lustrep4/scratch/project_465000527/anemoi/datasets/CERRA/cerra-rr-an-oper-0001-mars-5p5km-1984-2020-3h-v2-rmi.zarr
            rename:
                2t_2: 2t
                2d_2: 2d
                10u_10: 10u
                10v_10: 10v
                msl_0: msl
            rescale:
                tp:
                  scale: 0.001
                  offset: 0.0
          - dataset: /pfs/lustrep4/scratch/project_465000527/anemoi/datasets/CERRA/cerra-rr-an-oper-0001-mars-5p5km-1984-2020-3h-v2-z_sfc-rmi.zarr

  select: 
    - 2t
    - 2d
    - 10u
    - 10v
    - msl
    - sp
    - lsm
    - skt
    - z
    - tp
    - u_100
    - u_150
    - u_200
    - u_300
    - u_400
    - u_500
    - u_700
    - u_850
    - u_925
    - u_1000
    - v_100
    - v_150
    - v_200
    - v_300
    - v_400
    - v_500
    - v_700
    - v_850
    - v_925
    - v_1000
    - t_100
    - t_150
    - t_200
    - t_300
    - t_400
    - t_500
    - t_700
    - t_850
    - t_925
    - t_1000
    - q_100
    - q_150
    - q_200
    - q_300
    - q_400
    - q_500
    - q_700
    - q_850
    - q_925
    - q_1000
    - z_100
    - z_150
    - z_200
    - z_300
    - z_400
    - z_500
    - z_700
    - z_850
    - z_925
    - z_1000
    - cos_latitude
    - cos_longitude
    - sin_latitude
    - sin_longitude
    - cos_julian_day
    - cos_local_time
    - sin_julian_day
    - sin_local_time
    - insolation