defaults:
- data: zarr
- dataloader: multi_domain
- diagnostics: evaluation
- hardware: slurm
- graph: multi_domain_stretch
- model: dynamic_graphtransformer
- training: default
- _self_


### This file is for local experimentation.
##  When you commit your changes, assign the new features and keywords
##  to the correct defaults.
# For example to change from default GPU count:
# hardware:
#   num_gpus_per_node: 1

diagnostics:
  log:
    interval: 10
    mlflow:
      enabled: True
      offline: False
      authentication: True
      experiment_name: 'knmi-lumi-anemoi-cerra-sg'
      project_name: 'Anemoi'
      log_model: False
      tracking_uri: 'https://mlflow.ecmwf.int'
    wandb:
      enabled: False
  print_memory_summary: True
  show_entire_globe: False
  plot:
    callbacks: []
hardware:
  num_gpus_per_node: 8
  num_nodes: 1
  num_gpus_per_model: 4
model:
  num_channels: 128
  # output_mask: cutout # it must be a node attribute of the output nodes
dataloader:
  limit_batches:
    training: 10
    validation: 10
training:
  max_epochs: 20
  validation_metrics:
  # loss class to initialise
  - _target_: anemoi.training.losses.mse.WeightedMSELoss
    # Scalars to include in loss calculation
    # Cannot scale over the variable dimension due to possible remappings.
    # Available scalars include:  
    # - 'loss_weights_mask': Giving imputed NaNs a zero weight in the loss function
    # Use the `scale_validation_metrics` section to variable scale.
    scalars: []
    # other kwargs
    ignore_nans: True
  - _target_: anemoi.training.losses.multidomain_mse.MultiDomainMSELoss
    loss_name: "ARA"
    ignore_nans: True
  - _target_: anemoi.training.losses.multidomain_mse.MultiDomainMSELoss
    loss_name: "MEPS"
    ignore_nans: True



