defaults:
- data: zarr
- dataloader: multi_domain
- diagnostics: evaluation
- hardware: slurm
- graph: multi_domain_stretch
- model: dynamic_graphtransformer
- training: default
- _self_


### This file is for local experimentation.
##  When you commit your changes, assign the new features and keywords
##  to the correct defaults.
# For example to change from default GPU count:
# hardware:
#   num_gpus_per_node: 1
graph:
  overwrite: True
  nodes:
    hidden:
      node_builder:
        _target_: anemoi.graphs.nodes.StretchedTriNodes
        lam_resolution: 10
        global_resolution: 7
        reference_node_name: ${graph.data}
        mask_attr_name: cutout
        margin_radius_km: 11

diagnostics:
  log:
    mlflow:
      enabled: True
      offline: True
      authentication: True
      experiment_name: 'multi-domain-experiments'
      project_name: 'Anemoi'
      log_model: False
      tracking_uri: 'https://mlflow.ecmwf.int'
    wandb:
      enabled: False
  print_memory_summary: True
  enable_checkpointing: True
  # every_n_minutes:
  #   save_frequency: 1 # Approximate, as this is checked at the end of training steps
  show_entire_globe: False
hardware:
  files: 
    warm_start: /pfs/lustrep4/scratch/project_465000527/anemoi/experiments/n320_arome_meps_pretrain/anemoi-by_epoch-epoch_038-step_019503.ckpt
    # warm_start: /pfs/lustrep4/scratch/project_465000527/buurmans/DE_330_WP14/Anemoi/multi-domain-training/output/checkpoint/e659e66325464922979909ad7b451d44/anemoi-by_time-epoch_029-step_011774.ckpt
    # warm_start: /pfs/lustrep4/scratch/project_465000527/salihiar/multi-domain-setup/cloudy-skies-exp/output/fc6h/c1024b16/checkpoint/e0ac0b53da2e4d4a8b1332bdc8aa1f1a/last.ckpt ## WATCH OUT THIS IS CLOUDY SKIES CHECKPOINT #####
  num_gpus_per_node: 8
  num_nodes: 1
  num_gpus_per_model: 8
model:
  num_channels: 1024

training:
  node_loss_weights:
    MEPS:
      _target_: anemoi.training.losses.nodeweights.ReweightedGraphNodeAttribute
      target_nodes: ${graph.data}
      scaled_attribute: cutout
      weight_frac_of_total: 0.23
      node_attribute: area_weight
  run_id: 
  transfer_learning: True
  load_weights_only: True
  max_steps: 12000

  lr:
    rate: 0.4e-5 #local_lr
    iterations: ${training.max_steps} # NOTE: When max_epochs < max_steps, scheduler will run for max_steps
    min: 3e-7 #Not scaled by #GPU
    warmup_t: 1000

  validation_metrics: 
    - _target_: anemoi.training.losses.mse.WeightedMSELoss
      # Scalars to include in loss calculation
      # Cannot scale over the variable dimension due to possible remappings.
      # Available scalars include:  
      # - 'loss_weights_mask': Giving imputed NaNs a zero weight in the loss function
      # Use the `scale_validation_metrics` section to variable scale.
      scalars: []
      # other kwargs
      ignore_nans: True
    - _target_: anemoi.training.losses.multidomain_mse.MultiDomainMSELoss
      scalars: ['limited_area_mask_MEPS']
      loss_name: "MEPS"
      inside_lam: True
      wmse_contribution: True
      ignore_nans: True


dataloader:
  num_workers:
    training: 7
    validation: 7
    test: 1
    predict: 1
  limit_batches:
    training: 400
    validation: null
  training_periods:
    MEPS:
      start: 2020-02-05 
      end: 2022-05-31

  validation_periods:
    MEPS:
      start: 2022-06-01 
      end: 2023-05-31
  regional_datasets:
    MEPS: 
      dataset: /pfs/lustrep4/scratch/project_465000527/anemoi/datasets/MEPS/aifs-meps-2.5km-2020-2024-6h-v6.zarr

  select: 
      - 10u
      - 10v
      - 2d
      - 2t
      - cos_julian_day
      - cos_latitude
      - cos_local_time
      - cos_longitude
      - insolation
      - lsm
      - msl
      - q_100
      - q_1000
      - q_150
      - q_200
      - q_250
      - q_300
      - q_400
      - q_50
      - q_500
      - q_700
      - q_850
      - q_925
      - sin_julian_day
      - sin_latitude
      - sin_local_time
      - sin_longitude
      - skt
      - sp
      - t_100
      - t_1000
      - t_150
      - t_200
      - t_250
      - t_300
      - t_400
      - t_50
      - t_500
      - t_700
      - t_850
      - t_925
      - tcw
      - tp
      - u_100
      - u_1000
      - u_150
      - u_200
      - u_250
      - u_300
      - u_400
      - u_50
      - u_500
      - u_700
      - u_850
      - u_925
      - v_100
      - v_1000
      - v_150
      - v_200
      - v_250
      - v_300
      - v_400
      - v_50
      - v_500
      - v_700
      - v_850
      - v_925
      - w_100
      - w_1000
      - w_150
      - w_200
      - w_250
      - w_300
      - w_400
      - w_50
      - w_500
      - w_700
      - w_850
      - w_925
      - z
      - z_100
      - z_1000
      - z_150
      - z_200
      - z_250
      - z_300
      - z_400
      - z_50
      - z_500
      - z_700
      - z_850
      - z_925

  # select: 
  #     - 2t
  #     - 2d
  #     - 10u
  #     - 10v
  #     - msl
  #     - sp
  #     - lsm
  #     - z
  #     - tp
  #     - skt
  #     - tcw
  #     - u_50
  #     - u_100
  #     - u_150
  #     - u_200
  #     - u_250
  #     - u_300
  #     - u_400
  #     - u_500
  #     - u_700
  #     - u_850
  #     - u_925
  #     - u_1000
  #     - v_50
  #     - v_100
  #     - v_150
  #     - v_250
  #     - v_200
  #     - v_300
  #     - v_400
  #     - v_500
  #     - v_700
  #     - v_850
  #     - v_925
  #     - v_1000
  #     - w_50
  #     - w_100
  #     - w_150
  #     - w_200
  #     - w_250
  #     - w_300
  #     - w_400
  #     - w_500
  #     - w_700
  #     - w_850
  #     - w_925
  #     - w_1000
  #     - t_50
  #     - t_100
  #     - t_150
  #     - t_200
  #     - t_250
  #     - t_300
  #     - t_400
  #     - t_500
  #     - t_700
  #     - t_850
  #     - t_925
  #     - t_1000
  #     - q_50
  #     - q_100
  #     - q_150
  #     - q_200
  #     - q_250
  #     - q_300
  #     - q_400
  #     - q_500
  #     - q_700
  #     - q_850
  #     - q_925
  #     - q_1000
  #     - z_50
  #     - z_100
  #     - z_150
  #     - z_200
  #     - z_250
  #     - z_300
  #     - z_400
  #     - z_500
  #     - z_700
  #     - z_850
  #     - z_925
  #     - z_1000
  #     - "cos_latitude"
  #     - "cos_longitude"
  #     - "sin_latitude"
  #     - "sin_longitude"
  #     - "cos_julian_day"
  #     - "cos_local_time"
  #     - "sin_julian_day"
  #     - "sin_local_time"
  #     - "insolation"
