defaults:
  - graphtransformer_ens

dynamic_mode: True # Enables multi-domain
sub_graph_edge_index_name: edge_index
node_dim: 4 
edge_dim: 3

# For further modification please add sections you want to override in default
# graphtransformer_ens config file as listed above

model:
  _target_: anemoi.models.models.EnsembleMultiDomain

# model_type:
#   _target_: anemoi.models.models.AnemoiMultiDomain.EnsembleMultiDomain

processor:
  edge_dim: ${model.edge_dim}
  dynamic_mode: ${model.dynamic_mode}
  sub_graph_edge_index_name: ${model.sub_graph_edge_index_name}

encoder:
  edge_dim: ${model.edge_dim}
  dynamic_mode: ${model.dynamic_mode}
  sub_graph_edge_index_name: ${model.sub_graph_edge_index_name}


decoder:
  edge_dim: ${model.edge_dim}
  dynamic_mode: ${model.dynamic_mode}
  sub_graph_edge_index_name: ${model.sub_graph_edge_index_name}




